### ISSUE TITLE
Outdated Kernel Sources

### ISSUE THREAD

**Issue by SayanthD** [realme-kernel-opensource/realmeQ_realme5Pro-kernel-source#3]
This source you guys provided for RMX1971 is really buggy. Not even sure how old it is. You guys maybe shared what you got as base to work on.

Why do you guys release broken/incomplete kernels and expects community to develop roms? Like even you send Realme X to few devs but provided incomplete kernels

Its a shame to see mid-range flagship hardware get destroyed by software which gives headaches.

**Just push the updated commit, but not all at once. Commit changes periodically and give proper history**. Then only it will be easier to track and fix.

Just look at your competitors and learn how they became 'Number One in India'. 
_**The two things that is stopping Realme from becoming top brand is its bloated ColorOS and poor community support**_.

Hope you guys read these issues and bring some fresh hot commits to complete the kernel.

**Comment by realme-kernel-opensource** [comment]
font{
        line-height: 1.7;
    }


    
hi,sirthks for your feedback. you suggestion maybe is right.we are considering about this. but the kernel code about device drivers are uploaded. so any question about compile and port, you can tell me directly.                



    On 10/28/2019 22:51，Sayanth Dinesh<notifications@github.com> wrote： 


This source you guys provided for RMX1971 is really buggy. Not even sure how old it is. You guys maybe shared what you got as base to work on.
Why do you guys release broken/incomplete kernels and expects community to develop roms? Like even you send Realme X to few devs but provided incomplete kernels
Its a shame to see mid-range flagship hardware get destroyed by software which gives headaches.
Just push the updated commit, but not all at once. Commit changes periodically and give proper history. Then only it will be easier to track and fix.
Just look at your competitors and learn how they became 'Number One in India'.
The two things that is stopping Realme from becoming top brand is its bloated ColorOS and poor community support.
Hope you guys read these issues and bring some fresh hot commits to complete the kernel.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.


        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
